################################### Hungarian language #####################################
[hu]
languageName = "Hu"
languageCode = "hu-HU"
contentDir = "content/magyar"
weight = 1
home = "Nyitóoldal"
# footer content
footer_content = "Megvalósítjuk terveit. Minsőgés és megbízhatóság. <br/> Minden egyes alkalommal."
# copyright
copyright = "© 2022 ― Minden jog fenntartva!"

################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
# footer content
footer_content = "Making your vision become a reality. Quality. Safety. Reliability. Every time. Let’s construct a better tomorrow for future generations."
# copyright
copyright = "© 2022 ― All rights reserved!"
