############# Hun navigation ##############

# main menu
[[main]]
name = "Rólunk"
url = "about"
weight = 1

[[main]]
name = "Projektek"
url = "contact"
weight = 2

[[main]]
name = "Referenciák"
url = "references"
weight = 2

[[main]]
name = "Kapcsolat"
url = "contact"
weight = 3

[[main]]
weight = 8
name = "Egyéb"
hasChildren = true

  [[main]]
  parent = "Egyéb"
  name = "All Projects"
  url = "project"
  weight = 1

  [[main]]
  parent = "Egyéb"
  name = "Service"
  url = "service"
  weight = 2

  [[main]]
  parent = "Egyéb"
  name = "Blog"
  url = "blog"
  weight = 3

  [[main]]
  parent = "Egyéb"
  name = "Team"
  url = "team"
  weight = 4


# footer menu
[[footer]]
name = "Adatvédelmi tájékoztató"
url = "privacy-policy"
weight = 2