############# Hun navigation ##############

# main menu
[[main]]
name = "Rólunk"
url = "about"
weight = 1

[[main]]
name = "Projektek"
url = "project"
weight = 2

[[main]]
name = "Referenciák"
url = "references"
weight = 2

[[main]]
name = "Kapcsolat"
url = "contact"
weight = 3

[[main]]
name = "Pályázatok"
url = "tender"
weight = 3

[[main]]
weight = 8
name = "Egyéb"
hasChildren = true

  [[main]]
  parent = "Egyéb"
  name = "Letöltések"
  url = "downloads"
  weight = 1

  [[main]]
  parent = "Egyéb"
  name = "Adatvédelmi tájékoztató"
  url = "privacy-policy"
  weight = 2


# footer menu
[[footer]]
name = "Adatvédelmi tájékoztató"
url = "privacy-policy"
weight = 1