########################### Default parameters ######################
logo = "images/logo.png"
logo_width = "149px"
logo_footer = "images/favicon.ico"
favicon = "images/favicon.ico"
# top header
top_header = true
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "2528 Máriahalom"
mobile = ""
email = "kapcsolat@egyenesut.eu"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "G-T8TYZ1N0T0" # your id
# page sidebar quick contact form
quick_contact = true
# search
search = false

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "get a quote"
link = "contact"

# Subscription
[subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[gmap]
enable = true
gmap_api = "AIzaSyDzEjAtXS1LQCnePriqtkM9inDcr1QdMsc"
map_latitude = "47.6273"
map_longitude = "18.7079"
map_marker = "images/marker.png"
map_marker_name = "Egyenes Út"

########################### social icon ############################
#[[social]]
#icon = "fab fa-facebook"
#link = "https://facebook.com/themefisher"

#[[social]]
#icon = "fab fa-twitter"
#link = "https://twitter.com/themefisher"

#[[social]]
#icon = "fab fa-github"
#link = "https://github.com/themefisher"

#[[social]]
#icon = "fab fa-instagram"
#link = "https://instagram.com/themefisher"